# Generated by Django 5.2.7 on 2025-10-27 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True)),
                ('temp_c', models.FloatField()),
                ('co2_ppm', models.IntegerField()),
                ('noise_dba', models.FloatField()),
                ('humidity_pct', models.FloatField()),
                ('ambiente', models.CharField(choices=[('óptimo', 'Óptimo'), ('aceptable', 'Aceptable'), ('crítico', 'Crítico')], max_length=15)),
                ('tvoc_index', models.IntegerField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Medición',
                'verbose_name_plural': 'Mediciones',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MetricSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('sensor', models.CharField(max_length=80)),
                ('measured_param', models.CharField(max_length=120)),
                ('input_desc', models.CharField(max_length=120)),
                ('unit', models.CharField(max_length=20)),
                ('range_text', models.TextField()),
                ('use_in_reports', models.CharField(max_length=200)),
                ('thresholds', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Especificación de parámetro',
                'verbose_name_plural': 'Especificaciones de parámetros',
                'ordering': ['code'],
            },
        ),
    ]
