# Generated by Django 5.2.7 on 2025-10-26 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='measurement',
            constraint=models.UniqueConstraint(fields=('created_at', 'temp_c', 'co2_ppm', 'noise_dba', 'humidity_pct'), name='uniq_measurement_at_values'),
        ),
    ]
